name: deploy-shared-services

on:
  push:
    paths:
      - shared-services/**
      - etc/shared-services.tfvars
      - etc/global.tfvars
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/deploy-shared-workflow.yml
    with:
      environment: shared-services
    secrets:
      AWS_IAM_ROLE_TO_ASSUME_ARN: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      GH_PAT: ${{ secrets.GH_PAT }}
